# Storage Section
# Here you can specify where to save the surveys results
# There are three options: MYSQL, MongoDB or flatFile
storage:
  type: flatFile
  username: test
  password: test
  host: localhost
  port: 7777
  database: Bugs-reports

#Time (inactive seconds) to wait before abandoning the player report conversation.
time-out: 360

labels:
  - lag
  - redstone

main-inventory:
  title: "&7&lReport page: %actual-page%"
  items:
    reports:
      material: PAPER
      name: '&8report-%report_id%'
      lore:
        - 'Report status: %report_status%'
      glow: false
    next-page:
      material: ARROW
      name: '&7Next page'
      lore:
        - '&bClick here to go to page %next_page%'
      glow: false
    previous-page:
      material: ARROW
      name: '&7Previous page'
      lore:
        - '&bClick here to go to page %previous_page%'
      glow: false

report-inventory:




##########MENU##########
report-item: 'PAPER'