# Storage Section
# Here you can specify where to save the surveys results
# There are three options: MYSQL, h2 or flatFile
storage:
  type: h2
  username:
  password:
  ip:
  port:
  database:

# Set the permission players need to use the report command. Leave as '' for no permission.
use-permission: 'bugreport.report'

#Time (inactive seconds) to wait before abandoning the player report conversation.
time-out: 360

labels:
  - lag
  - redstone
  - end
  - nether
  - overworld

main-inventory:
  title: "&7&lReport page: %actual-page%"
  items:
    reports:
      material: PAPER
      name: '&8report-%report_id%'
      lore:
        - 'Report status: %report_status%'
      glow: false
    next-page:
      material: ARROW
      name: '&7Next page'
      lore:
        - '&bClick here to go to page %next_page%'
      glow: false
    previous-page:
      material: ARROW
      name: '&7Previous page'
      lore:
        - '&bClick here to go to page %previous_page%'
      glow: false

##########MENU##########
report-item: 'PAPER'